name:                apecs-snake
version:             0.1.0.0
github:              "willisplummer/apecs-snake"
license:             BSD3
author:              "willis plummer"
maintainer:          "willisplummer@gmail.com"
copyright:           "2020 willis plummer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/willisplummer/apecs-snake#readme>

dependencies:
- base >= 4.7 && < 5
- apecs
- apecs-gloss
- linear
- random

library:
  source-dirs: src

executables:
  apecs-snake-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - apecs-snake

tests:
  apecs-snake-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - apecs-snake
